Added the ability to create temporary keys
deepgram/node-sdk pull request #19
Opened 2021-12-16 01:46 UTC by MichaelJolley

Updated the `keys.create` function to allow new `expirationDate` or `timeToLive` values. These are optional and one at most can be provided. Providing both will throw an error.

2021-12-17 15:49 UTC, phazonoverload requested changes
Looks good to me - before approval can you show an example (even just in this thread) of creating a key with `expiration_date` and one with `time_to_live_in_seconds`?

2021-12-17 15:56 UTC, MichaelJolley commented
Sure thing.

Expiration Date
```js
deepgram.keys.create(PROJECT_ID, COMMENT, ["member"], new Date());
```


TTL
```js
deepgram.keys.create(PROJECT_ID, COMMENT, ["member"], null, 30);
```

2021-12-17 15:59 UTC, phazonoverload commented
Would it be feasible to allow that third param to be a number OR a date, and dependent on type it will act differently? Not sure if it's the right approach but welcome thoughts.

2021-12-17 22:31 UTC, natalierutgers approved these changes

2021-12-18 05:12 UTC, MichaelJolley commented
@phazonoverload I like that idea, but what would you name that parameter?

2021-12-20 10:50 UTC, phazonoverload commented
`expiry` I think works

2022-01-11 23:21 UTC, MichaelJolley commented
Updated based on our conversations to take an optional object that can only contain expirationDate or timeToLive

2022-01-12 08:43 UTC, phazonoverload approved these changes

2022-01-12 08:44 UTC, phazonoverload commented
Thanks so much for this @MichaelJolley

2022-01-12 08:44 UTC, merged