fix: fix types to match current api response
deepgram/node-sdk pull request #26
Opened 2022-02-25 20:55 UTC by lukeocodes

updated the API key type to match the current API response

fixes #25

2022-02-25 21:08 UTC, briancbarrow approved these changes

2022-02-25 22:19 UTC, lukeocodes commented
@MichaelJolley the question is if this should be a major version bump or whether we should parse the response and output the original format for compatibility.

What do you think?

2022-02-25 23:24 UTC, MichaelJolley requested changes
I added comments, then realized this is the wrong way to fix this issue. In this PR, we're modifying the `Key` type. That type is currently used by the [KeyResponse](https://github.com/deepgram/node-sdk/blob/main/src/types/keyResponse.ts) type and the [Keys](https://github.com/deepgram/node-sdk/blob/main/src/keys.ts) static class as the return type of the create & get functions. Modifying the `Key` type would provide the incorrect return type for those methods. 

Instead, we should create a new `Member` type and add it as an optional property to the `KeyResponse` type, like:

```ts
import { Key } from "./key";
import { Member } from "./member";

/**
 * Response from the Deepgram API to list keys
 */
export type KeyResponse = {
  /**
   * Array of API keys associated with the project
   */
  api_keys: Array<{
    /**
    * Optional member associated with the API key
    */
    member?: Member;
    
    /**
    * API key
    */ 
    api_key: Key;
  }>;
};
```

2022-02-25 23:24 UTC, MichaelJolley commented on src/types/key.ts
> +export declare type Key = {
declare isn't needed here.

2022-02-25 23:24 UTC, MichaelJolley commented on src/types/key.ts
> +   * Api key member object
API (capitalized since it's an abbreviation)

2022-02-25 23:24 UTC, MichaelJolley commented on src/types/key.ts
> +  member: {
The member object is nullable.

```ts
member?: {
```

2022-02-25 23:24 UTC, MichaelJolley commented on src/types/key.ts
> +   * Api key object
API (capitalized since it's an abbreviation)

2022-02-25 23:41 UTC, MichaelJolley commented
@lukeocodes answering the other question around SemVer: ideally we would retain the old typing and provide the previous output as well (if possible) and flag the properties we know are wrong/outdated as deprecated to be removed at a future date.

2022-02-26 04:09 UTC, lukeocodes commented
> I added comments, then realized this is the wrong way to fix this issue. In this PR, we're modifying the `Key` type. That type is currently used by the [KeyResponse](https://github.com/deepgram/node-sdk/blob/main/src/types/keyResponse.ts) type and the [Keys](https://github.com/deepgram/node-sdk/blob/main/src/keys.ts) static class as the return type of the create & get functions. Modifying the `Key` type would provide the incorrect return type for those methods. 
> 
> Instead, we should create a new `Member` type and add it as an optional property to the `KeyResponse` type, like:
> 
> ```ts
> import { Key } from "./key";
> import { Member } from "./member";
> 
> /**
>  * Response from the Deepgram API to list keys
>  */
> export type KeyResponse = {
>   /**
>    * Array of API keys associated with the project
>    */
>   api_keys: Array<{
>     /**
>     * Optional member associated with the API key
>     */
>     member?: Member;
>     
>     /**
>     * API key
>     */ 
>     api_key: Key;
>   }>;
> };
> ```

I'll look more closely at this. Something is yelling at me that this isn't the format being returned but I could be wrong.

Definitely considering tackling a test suit next

2022-02-26 07:35 UTC, lukeocodes commented
> @lukeocodes answering the other question around SemVer: ideally we would retain the old typing and provide the previous output as well (if possible) and flag the properties we know are wrong/outdated as deprecated to be removed at a future date.

I'm not sure I know how to achieve this without introducing a promise to wrap around _request in order to modify the output, with some property to switch to the new output?

2022-02-26 09:49 UTC, lukeocodes commented
Types for Key and Member now match the API response. I've changed the existing Member type as it didn't appear to be used anywhere else yet

2022-03-01 02:44 UTC, MichaelJolley approved these changes

2022-03-01 02:44 UTC, merged